# Copyright (c) 2026 Twin Vector Labs LLC.
# All rights reserved.

"""Which operations U on Z(T^2)=C^4 are Dijkgraaf-Witten realizable.

The companion runnable for the realizable-image report (#194), the payoff to the
twisted-cylinder builder (#193). It re-runs the labeled operation sweep against
the *enriched* realizable DW 2-boundary map image and reports the now
non-degenerate separating property.

Background. The DW functor sends a cobordism W : T^2 -> T^2 to a linear map on
Z(T^2) = C[H^1(T^2;Z_2)] = C^4 (the flat-Z_2-connection basis, classes indexed
0=[trivial], 1=[a], 2=[b], 3=[a+b]). With only the order-preserving product
cylinder available the realizable image was the single point {I_4}, so the
realizability question "what distinguishes a DW-realizable U" was degenerate.
``Cobordism.twistedCylinder(Sigma, phi)`` threads the two boundary copies of
Sigma through a finite-order simplicial automorphism phi, and ``Dijkgraaf
Witten.map()`` returns the permutation phi induces on the holonomy classes. Two
generators suffice:

  * the coordinate swap phi:(u,v)->(v,u) on the 9-vertex product torus
    T^2 = SimplicialProduct(dDelta^2, dDelta^2) -- the transposition (1 2) that
    exchanges [a]<->[b] and fixes [0],[a+b];
  * the multiplier i->2i (mod 7) on the 7-vertex Moebius torus -- the order-3
    rotation (1 2 3) that cycles [a]->[b]->[a+b] and fixes [0].

Generated by matrix multiplication these two close to a group of exactly 6
elements: the full S_3 on the three non-trivial classes, fixing the trivial one
-- the permutation representation of GL(2,Z_2) = SL(2,Z_2) acting on
H^1(T^2;Z_2). That is the realizable set.

The sweep then reads >= 150 labeled operations U (4x4) through the genuine
machinery (``DijkgraafWitten.amplitude``, ``ChoiJamiolkowski.transition
Amplitude``, ``BoundaryStateSpace.state``) and records, for each,

  * gap_to_S3 = min over the 6 realizable maps g of ||U - g||  (the live metric);
  * gap_to_I4 = ||U - I_4||                                    (the old metric);
  * realizable := gap_to_S3 < tol;

plus the candidate separating properties. The discriminating family is the full
24 of S_4's 4x4 permutation matrices: exactly the 6 that fix index 0 (and so
permute {1,2,3}) are realizable, the other 18 are not -- the clean separation.

The separator. realizable(U) <=> U is a 0/1 permutation matrix fixing the
trivial class index 0 <=> U is the permutation rep of a GL(2,Z_2) automorphism
of H^1(T^2;Z_2). The fact that *every* permutation of the three non-trivial
classes is GF(2)-linear (any two distinct non-zero vectors of (Z_2)^2 are a
basis, so the image of [a+b] is forced to the sum) is exactly why the realizable
image is the *full* S_3 and not a proper subgroup -- and why distance-to-S_3,
not distance-to-I_4, now governs the gap.

Run:  python examples/cobordism/realizable_image_sweep.py
      (--help for options; the raw full sweep table defaults to /tmp/cobordism
      and is NOT committed -- attach it to the issue/PR to pin a result. The
      script is the committed artifact.)

Exit status is 0 iff the verdicts match expectation: the six DW maps close to
S_3; of the 24 permutations exactly the 6 holonomy ones are realizable; I_4 is
realizable; and a Haar/Hadamard sample is not.
"""

from __future__ import annotations

# Honor the shared-box CPU cap before numpy / the C++ ext pull in a BLAS.
import os

for _var in ("OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS",
             "BLIS_NUM_THREADS"):
    os.environ.setdefault(_var, "4")

import argparse  # noqa: E402
import cmath     # noqa: E402
import csv       # noqa: E402
import itertools  # noqa: E402

import numpy as np  # noqa: E402

import tessera  # noqa: E402

cob = tessera.cobordism
DijkgraafWitten = cob.DijkgraafWitten
Cocycle = cob.Cocycle
Cobordism = cob.Cobordism
ChoiJamiolkowski = tessera.quantum.ChoiJamiolkowski

DIM = 4                       # dim Z(T^2) = 2^{b_1(T^2)} = 4
REALIZABLE_TOL = 1e-7         # realizable := gap_to_S3 < REALIZABLE_TOL
OUT_DIR = "/tmp/cobordism"


# --------------------------------------------------------------------------- #
# Surface fixtures -- the #193 idiom, reused verbatim so the two generator maps
# share the holonomy-class indexing that lets them compose.
# --------------------------------------------------------------------------- #
def _build(topology):
    signature = tessera.Signature(topology.dimension(), tessera.Lorentzian)
    metric = tessera.Metric(True, signature)
    spacetime = tessera.Spacetime(metric, tessera.CDT, 1.0, 1.0,
                                  tessera.PREFERRED, topology)
    spacetime.build()
    return spacetime


def _circle():
    # S^1 = dDelta^2, the minimal triangle-boundary circle (3 vertices).
    return tessera.SimplexBoundarySphere(1)


def _torus_topology():
    # T^2 = S^1 x S^1, 9 vertices, productId(u, v) = 3u + v.
    return tessera.SimplicialProduct(_circle(), _circle())


def _product_torus():
    return _build(_torus_topology())


# The coordinate swap phi(u, v) = (v, u): 3u+v -> 3v+u (an order-2 automorphism).
_SWAP = [v * 3 + u for u in range(3) for v in range(3)]

# The minimal 7-vertex (Moebius) torus: the two Z_7-orbits of {0,1,3}, {0,2,3}.
_SEVEN_VERTEX_TRIANGLES = sorted({
    tuple(sorted(((i) % 7, (i + step) % 7, (i + 3) % 7)))
    for i in range(7) for step in (1, 2)})


def _seven_vertex_torus():
    signature = tessera.Signature(2, tessera.Lorentzian)
    metric = tessera.Metric(True, signature)
    spacetime = tessera.Spacetime(metric, tessera.CDT, 1.0, 1.0,
                                  tessera.PREFERRED, None)
    vertices = [spacetime.createVertex(i) for i in range(7)]
    for triangle in _SEVEN_VERTEX_TRIANGLES:
        spacetime.createSimplex([vertices[i] for i in triangle])
    return spacetime


def _multiplier(m, n):
    """The multiplier automorphism i -> m*i (mod n)."""
    return [(m * i) % n for i in range(n)]


def _twisted_map(surface, phi, cocycle=Cocycle.Trivial):
    """The DW boundary map of the phi-twisted cylinder over a surface (4x4)."""
    twisted = Cobordism.twistedCylinder(surface, phi)
    return np.asarray(DijkgraafWitten(twisted, cocycle).map())


# --------------------------------------------------------------------------- #
# The enriched realizable image: the S_3 = GL(2,Z_2) holonomy-permutation group.
# --------------------------------------------------------------------------- #
class RealizableImage:
    """The realizable DW 2-boundary map image, generated from twisted cylinders.

    Builds the swap (order 2) and the 3-cycle (order 3) DW maps through the
    genuine ``twistedCylinder`` + ``DijkgraafWitten.map`` machinery, closes the
    matrix group they generate, and certifies it is the 6-element S_3 of
    GL(2,Z_2) holonomy permutations -- each a 0/1 permutation fixing the trivial
    class and acting GF(2)-linearly on H^1(T^2;Z_2).
    """

    def __init__(self):
        self.swap = self._real(_twisted_map(_product_torus(), _SWAP))
        self.three_cycle = self._real(
            _twisted_map(_seven_vertex_torus(), _multiplier(2, 7)))
        self.maps = self._close_group([self.swap, self.three_cycle])

    @staticmethod
    def _real(matrix):
        # The DW permutation maps are real 0/1 matrices; drop the +0j.
        return np.asarray(matrix).real

    @staticmethod
    def _key(matrix):
        return tuple(np.round(np.asarray(matrix).real).astype(int).reshape(-1))

    @classmethod
    def _close_group(cls, generators):
        """The matrix group generated by `generators` (breadth-first closure)."""
        identity = np.eye(DIM)
        group = {cls._key(identity): identity}
        frontier = [identity]
        while frontier:
            element = frontier.pop()
            for generator in generators:
                product = generator @ element
                key = cls._key(product)
                if key not in group:
                    group[key] = product
                    frontier.append(product)
        return list(group.values())

    def gap(self, matrix):
        """min over the realizable maps g of ||matrix - g||_F (distance to S_3)."""
        return float(min(np.linalg.norm(matrix - g) for g in self.maps))

    def contains(self, matrix, tol=REALIZABLE_TOL):
        return self.gap(matrix) < tol

    # -- certification ----------------------------------------------------- #
    def certify(self):
        """Assert the realizable set is exactly the 6 GL(2,Z_2) permutations.

        Returns the list of (permutation-dict) for reporting.
        """
        assert len(self.maps) == 6, \
            f"the realizable image must be S_3 (order 6), got {len(self.maps)}"
        perms = []
        for matrix in self.maps:
            assert is_permutation(matrix), "every realizable map is a permutation"
            perm = permutation_of(matrix)
            assert perm[0] == 0, "every realizable map fixes the trivial class [0]"
            assert is_gf2_linear(perm), \
                "every realizable map is a GF(2)-linear automorphism of H^1"
            perms.append(perm)
        # The realizable set == exactly the S_4 permutations that fix index 0.
        fixers = [permutation_matrix(p)
                  for p in itertools.permutations(range(DIM)) if p[0] == 0]
        assert len(fixers) == 6
        for fixer in fixers:
            assert any(np.allclose(fixer, g) for g in self.maps), \
                "every index-0-fixing permutation must be realizable"
        # Group axioms on the realized matrices: closed under product and inverse.
        keys = {self._key(g) for g in self.maps}
        for a in self.maps:
            assert self._key(a.T) in keys, "closed under inverse (transpose)"
            for b in self.maps:
                assert self._key(a @ b) in keys, "closed under product"
        return perms


# --------------------------------------------------------------------------- #
# The genuine bridge machinery: the holonomy-basis amplitude reading.
# --------------------------------------------------------------------------- #
class BridgeMachinery:
    """Reads an operation U through the same classes the bridge experiment uses.

    ``operation_amplitudes(U)`` returns the 4x4 matrix
    <e_i|U|e_j> = ChoiJamiolkowski.transitionAmplitude over the holonomy basis,
    and the cylinder's metric-free state sum Z_DW = DijkgraafWitten.amplitude on
    BoundaryStateSpace.state(e_i) reproduces I_4 -- so the realizable identity
    map read two independent ways agrees, anchoring the gap metrics in the
    genuine machinery rather than in raw numpy.
    """

    def __init__(self):
        self.space = cob.BoundaryStateSpace(_product_torus())
        assert self.space.boundaryDimension() == DIM
        self._basis = [np.eye(DIM, dtype=complex)[i] for i in range(DIM)]
        cylinder = _build(tessera.SimplicialProduct(_torus_topology(),
                                                    tessera.SolidSimplex(1)))
        self._cylinder_dw = DijkgraafWitten(cylinder, Cocycle.Trivial)
        # Z_DW(cylinder) read through DijkgraafWitten.amplitude over the basis.
        self.z_dw = np.array(
            [[complex(self._cylinder_dw.amplitude(self._state(self._basis[i]),
                                                  self._state(self._basis[j])))
              for j in range(DIM)] for i in range(DIM)])
        assert np.allclose(self.z_dw, np.eye(DIM)), \
            "the product cylinder's DW map must read as I_4 through amplitude()"

    def _state(self, vector):
        return self.space.state(np.asarray(vector, dtype=complex))

    def operation_amplitudes(self, U):
        """<e_i|U|e_j> via ChoiJamiolkowski over the full holonomy basis (4x4)."""
        Uflat = [complex(z) for z in np.asarray(U, dtype=complex).reshape(-1)]
        amplitudes = np.empty((DIM, DIM), dtype=complex)
        for i in range(DIM):
            ei = [complex(z) for z in self._basis[i]]
            for j in range(DIM):
                ej = [complex(z) for z in self._basis[j]]
                amplitudes[i, j] = complex(
                    ChoiJamiolkowski.transitionAmplitude(ei, Uflat, ej, DIM, DIM))
        return amplitudes


# --------------------------------------------------------------------------- #
# Holonomy-class structure: permutation + GF(2)-linearity predicates. The three
# non-trivial classes are the non-zero vectors of (Z_2)^2: 1=[10], 2=[01],
# 3=[11].
# --------------------------------------------------------------------------- #
_CLASS_VECTOR = {0: (0, 0), 1: (1, 0), 2: (0, 1), 3: (1, 1)}
_VECTOR_CLASS = {v: c for c, v in _CLASS_VECTOR.items()}


def is_permutation(U, tol=1e-9):
    """True iff U is a 0/1 permutation matrix (one 1 per row and per column)."""
    matrix = np.asarray(U)
    if not np.all(np.isclose(matrix.imag, 0.0, atol=tol)):
        return False
    real = matrix.real
    if not np.all(np.isclose(real, 0.0, atol=tol)
                  | np.isclose(real, 1.0, atol=tol)):
        return False
    return bool(np.all(np.isclose(real.sum(axis=0), 1.0, atol=tol))
                and np.all(np.isclose(real.sum(axis=1), 1.0, atol=tol)))


def permutation_of(U):
    """The {row: column} permutation of a (rounded) 0/1 permutation matrix."""
    rounded = np.round(np.asarray(U).real).astype(int)
    return {r: int(np.argmax(rounded[r])) for r in range(rounded.shape[0])}


def _class_xor(a, b):
    """The holonomy class of v_a + v_b over Z_2 (group law of H^1(T^2;Z_2))."""
    va, vb = _CLASS_VECTOR[a], _CLASS_VECTOR[b]
    return _VECTOR_CLASS[(va[0] ^ vb[0], va[1] ^ vb[1])]


def is_gf2_linear(perm):
    """True iff `perm` is induced by a GF(2)-linear map of H^1(T^2;Z_2).

    A permutation of the holonomy classes is GF(2)-linear iff it fixes the
    trivial class and respects addition over Z_2: sigma(a+b)=sigma(a)+sigma(b).
    """
    if perm[0] != 0:
        return False
    return all(perm[_class_xor(a, b)] == _class_xor(perm[a], perm[b])
               for a in range(DIM) for b in range(DIM))


def is_holonomy_permutation(U, tol=1e-9):
    """The separator: U is a 0/1 permutation fixing the trivial class index 0.

    Equivalently (and the content of the result) U is the permutation rep of a
    GL(2,Z_2) = SL(2,Z_2) automorphism of H^1(T^2;Z_2).
    """
    if not is_permutation(U, tol):
        return False
    return is_gf2_linear(permutation_of(U))


def fixes_trivial_class(U, tol=1e-9):
    return bool(abs(complex(np.asarray(U)[0, 0]) - 1.0) < tol)


def permutation_matrix(perm):
    matrix = np.zeros((DIM, DIM), dtype=complex)
    for row, col in enumerate(perm):
        matrix[row, col] = 1.0
    return matrix


# --------------------------------------------------------------------------- #
# Auxiliary distinguishing properties (the prior-sweep battery).
# --------------------------------------------------------------------------- #
# The Z_2 flux operators on the holonomy basis: F1=(-1)^a, F2=(-1)^b. Commuting
# with both <=> diagonal in the holonomy basis (their joint eigenbasis).
F1 = np.diag([1.0, -1.0, 1.0, -1.0]).astype(complex)
F2 = np.diag([1.0, 1.0, -1.0, -1.0]).astype(complex)


def is_diagonal(U, tol=1e-9):
    matrix = np.asarray(U)
    return bool(np.linalg.norm(matrix - np.diag(np.diag(matrix))) < tol)


def flux_commutator(U):
    matrix = np.asarray(U)
    c1 = float(np.linalg.norm(matrix @ F1 - F1 @ matrix))
    c2 = float(np.linalg.norm(matrix @ F2 - F2 @ matrix))
    return max(c1, c2)


def unitarity(U):
    matrix = np.asarray(U)
    return float(np.linalg.norm(matrix.conj().T @ matrix - np.eye(DIM)))


def offdiag_weight(U):
    matrix = np.asarray(U)
    off = matrix - np.diag(np.diag(matrix))
    norm = np.linalg.norm(matrix)
    return float(np.linalg.norm(off) / norm) if norm > 0 else 0.0


# --------------------------------------------------------------------------- #
# Operation families (>= 150 ops). The 24 S_4 permutation matrices are the
# discriminating family. Fixed seeds for reproducibility.
# --------------------------------------------------------------------------- #
def _haar(seed):
    rng = np.random.default_rng(seed)
    z = (rng.standard_normal((DIM, DIM))
         + 1j * rng.standard_normal((DIM, DIM))) / np.sqrt(2)
    q, r = np.linalg.qr(z)
    return q @ np.diag(np.diag(r) / np.abs(np.diag(r)))


def _gl(seed):
    rng = np.random.default_rng(seed)
    return (rng.standard_normal((DIM, DIM))
            + 1j * rng.standard_normal((DIM, DIM)))


def _dft(n):
    j = np.arange(n)
    return np.exp(2j * np.pi * np.outer(j, j) / n) / np.sqrt(n)


_H2 = np.array([[1, 1], [1, -1]], dtype=complex) / np.sqrt(2)
_X = np.array([[0, 1], [1, 0]], dtype=complex)
_Y = np.array([[0, -1j], [1j, 0]], dtype=complex)
_Z = np.array([[1, 0], [0, -1]], dtype=complex)
_I2 = np.eye(2, dtype=complex)
_PAULI = {"I": _I2, "X": _X, "Y": _Y, "Z": _Z}


def operations(image):
    """Yield (label, family, U) triples spanning the operation families.

    `image` is the RealizableImage; its six maps are emitted as the ground-truth
    realizable family.
    """
    rng = np.random.default_rng(20240601)

    # ---- The realizable image itself (ground truth: gap_to_S3 = 0) --------- #
    for g in sorted(image.maps, key=lambda m: tuple(
            np.round(m.real).astype(int).reshape(-1))):
        perm = permutation_of(g)
        label = "s3_" + "".join(str(perm[i]) for i in range(DIM))
        yield label, "realizable_s3", g

    # ---- The 24 S_4 permutation matrices (the discriminating family) ------- #
    for p in itertools.permutations(range(DIM)):
        yield f"perm_{''.join(map(str, p))}", "permutation", permutation_matrix(p)

    # ---- Signed permutations (perm * +-1 row signs) ------------------------ #
    perms = list(itertools.permutations(range(DIM)))
    for k in range(20):
        p = perms[rng.integers(0, len(perms))]
        signs = rng.choice([1.0, -1.0], size=DIM)
        yield f"sperm_{k}", "signed_perm", permutation_matrix(p) * signs[:, None]

    # ---- Diagonal-in-holonomy ---------------------------------------------- #
    for bits in itertools.product((1, -1), repeat=DIM):       # all 16 +-1 signs
        tag = "".join("p" if b > 0 else "m" for b in bits)
        yield f"diag_{tag}", "diagonal", np.diag(np.array(bits, dtype=complex))
    roots4 = np.array([1, 1j, -1, -1j], dtype=complex)
    for k in range(16):
        d = roots4[rng.integers(0, 4, size=DIM)]
        yield f"diag_root4_{k}", "diagonal", np.diag(d)
    for k in range(16):
        d = np.exp(1j * rng.uniform(0, 2 * np.pi, size=DIM))
        yield f"diag_phase_{k}", "diagonal", np.diag(d)

    # ---- Holonomy-mixing (Hadamard / DFT / Haar / GL) ---------------------- #
    yield "hadamard4", "mixing", np.kron(_H2, _H2)
    block = np.eye(DIM, dtype=complex)
    block[1:3, 1:3] = _H2
    yield "hadamard_block_12", "mixing", block
    yield "dft4", "mixing", _dft(DIM)
    for k in range(48):
        yield f"haar_{k}", "mixing", _haar(1000 + k)
    for k in range(24):
        yield f"gl_{k}", "mixing", _gl(5000 + k)

    # ---- Interpolations (id -> target, staying on / off the lattice) ------- #
    identity = np.eye(DIM, dtype=complex)
    for seed in (7, 23):
        target = _haar(seed)
        for t in np.linspace(0.0, 1.0, 11):
            yield f"interp_id_haar{seed}_t{t:.2f}", "interp", \
                (1 - t) * identity + t * target
    swap_perm = permutation_matrix((1, 0, 3, 2))
    for t in np.linspace(0.0, 1.0, 11):
        yield f"interp_id_swap_t{t:.2f}", "interp", \
            (1 - t) * identity + t * swap_perm

    # ---- Two-qubit gates (some are holonomy permutations, most are not) ---- #
    cnot = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]],
                    dtype=complex)
    cz = np.diag([1, 1, 1, -1]).astype(complex)
    swap_gate = permutation_matrix((0, 2, 1, 3))
    iswap = np.array([[1, 0, 0, 0], [0, 0, 1j, 0], [0, 1j, 0, 0], [0, 0, 0, 1]],
                     dtype=complex)
    cphase = np.diag([1, 1, 1, cmath.exp(1j * np.pi / 4)]).astype(complex)
    yield "CNOT", "gate", cnot
    yield "CZ", "gate", cz
    yield "SWAP", "gate", swap_gate
    yield "iSWAP", "gate", iswap
    yield "CPHASE_pi4", "gate", cphase
    for a in ("I", "X", "Y", "Z"):
        for b in ("I", "X", "Y", "Z"):
            yield f"pauli_{a}{b}", "gate", np.kron(_PAULI[a], _PAULI[b])
    yield "H_x_I", "gate", np.kron(_H2, _I2)
    yield "I_x_H", "gate", np.kron(_I2, _H2)


# --------------------------------------------------------------------------- #
# The sweep.
# --------------------------------------------------------------------------- #
class OperationSweep:
    """Reads every labeled operation through the machinery and scores it.

    For each U records gap_to_S3 (distance to the realizable image), gap_to_I4
    (distance to the old single realizable point), the realizable verdict, and
    the candidate separating properties.
    """

    def __init__(self, image, machinery):
        self.image = image
        self.machinery = machinery
        self.identity = np.eye(DIM, dtype=complex)
        self.rows = []

    def run(self):
        for label, family, U in operations(self.image):
            U = np.asarray(U, dtype=complex)
            amplitudes = self.machinery.operation_amplitudes(U)   # genuine read
            # The machinery faithfully reads the operation back (sanity anchor).
            assert np.allclose(amplitudes, U, atol=1e-9), label
            gap_s3 = self.image.gap(amplitudes)
            gap_i4 = float(np.linalg.norm(amplitudes - self.identity))
            self.rows.append({
                "label": label,
                "family": family,
                "gap_to_S3": gap_s3,
                "gap_to_I4": gap_i4,
                "realizable": int(gap_s3 < REALIZABLE_TOL),
                "is_holonomy_perm": int(is_holonomy_permutation(U)),
                "is_permutation": int(is_permutation(U)),
                "fixes_trivial": int(fixes_trivial_class(U)),
                "is_diagonal": int(is_diagonal(U)),
                "flux_commutator": flux_commutator(U),
                "unitarity": unitarity(U),
                "offdiag_weight": offdiag_weight(U),
            })
        return self.rows

    # -- analysis ---------------------------------------------------------- #
    def separator_table(self):
        """Cross-tabulate each candidate predicate against the realizable verdict."""
        predicates = {
            "is_holonomy_perm (fixes [0] & permutes {1,2,3})":
                lambda r: r["is_holonomy_perm"],
            "is_permutation (any 0/1 perm of 4 classes)":
                lambda r: r["is_permutation"],
            "fixes_trivial_class [0]": lambda r: r["fixes_trivial"],
            "is_diagonal_in_holonomy": lambda r: r["is_diagonal"],
            "flux_commuting (||[U,F]||<1e-9)":
                lambda r: r["flux_commutator"] < 1e-9,
            "near_I4 (gap_to_I4 < 1e-7)": lambda r: r["gap_to_I4"] < 1e-7,
        }
        table = {}
        for name, predicate in predicates.items():
            tt = sum(1 for r in self.rows if predicate(r) and r["realizable"])
            tf = sum(1 for r in self.rows if predicate(r) and not r["realizable"])
            ft = sum(1 for r in self.rows
                     if not predicate(r) and r["realizable"])
            ff = sum(1 for r in self.rows
                     if not predicate(r) and not r["realizable"])
            table[name] = {"pred_work": tt, "pred_notwork": tf,
                           "notpred_work": ft, "notpred_notwork": ff,
                           "separates": tf == 0 and ft == 0}
        return table

    def permutation_verdict(self):
        """Of the 24 S_4 permutation matrices, which are realizable."""
        perms = [r for r in self.rows if r["family"] == "permutation"]
        realizable = [r for r in perms if r["realizable"]]
        return {"total": len(perms), "realizable": len(realizable),
                "labels": sorted(r["label"] for r in realizable)}

    def family_rates(self):
        rates = {}
        for r in self.rows:
            rates.setdefault(r["family"], [0, 0])
            rates[r["family"]][0] += r["realizable"]
            rates[r["family"]][1] += 1
        return rates


# --------------------------------------------------------------------------- #
# Reporting.
# --------------------------------------------------------------------------- #
def _fmt(value):
    return f"{value:.3g}" if isinstance(value, float) else str(value)


# A dozen-plus rows spanning realizable + non-realizable families, for the report.
REPRESENTATIVE = [
    "s3_0123", "s3_0213", "s3_0231",          # realizable: id, swap (12), 3-cycle
    "SWAP", "CNOT", "perm_0312",              # realizable gates / permutations
    "perm_1023", "perm_2301", "pauli_XX",     # permutations that move class [0]
    "CZ", "diag_pmpm", "hadamard4", "dft4", "haar_0",  # off the lattice
]


def print_report(image, sweep, perms):
    rows_by_label = {r["label"]: r for r in sweep.rows}
    print("=" * 78)
    print("Realizable DW image: the enriched S_3 holonomy-permutation group")
    print("=" * 78)
    print(f"  swap  (order 2): {_perm_str(permutation_of(image.swap))}   "
          f"3-cycle (order 3): {_perm_str(permutation_of(image.three_cycle))}")
    print(f"  <swap, 3-cycle> closes to {len(image.maps)} matrices "
          f"(asserted == S_3 = GL(2,Z_2) fixing class [0]):")
    for perm in sorted(perms, key=lambda p: tuple(p[i] for i in range(DIM))):
        print(f"      {_perm_str(perm)}   GF(2)-linear, fixes [0]")
    print()

    verdict = sweep.permutation_verdict()
    print(f"24 S_4 permutation matrices: {verdict['realizable']} realizable "
          f"(exactly those fixing index 0), {verdict['total'] - verdict['realizable']}"
          f" not.")
    print(f"   realizable permutations: {', '.join(verdict['labels'])}")
    print()

    print("Separator cross-tabulation (predicate vs realizable verdict):")
    print(f"   {'predicate':52} {'P&W':>4} {'P&!W':>5} {'!P&W':>5} "
          f"{'!P&!W':>6}  clean?")
    for name, t in sweep.separator_table().items():
        flag = "YES" if t["separates"] else "no"
        print(f"   {name:52} {t['pred_work']:>4} {t['pred_notwork']:>5} "
              f"{t['notpred_work']:>5} {t['notpred_notwork']:>6}  {flag}")
    print()

    print("Representative results (gap_to_S3 vs gap_to_I4):")
    print(f"   {'label':18} {'family':14} {'gap_to_S3':>10} {'gap_to_I4':>10} "
          f"{'realizable':>11} {'hol_perm':>9}")
    for label in REPRESENTATIVE:
        r = rows_by_label.get(label)
        if r is None:
            continue
        print(f"   {r['label']:18} {r['family']:14} {r['gap_to_S3']:>10.3e} "
              f"{r['gap_to_I4']:>10.3e} {r['realizable']:>11} "
              f"{r['is_holonomy_perm']:>9}")
    print()

    rates = sweep.family_rates()
    print("Realizable rate by family:")
    for family, (work, total) in sorted(rates.items()):
        print(f"   {family:16} {work:>3}/{total}")
    print()


def _perm_str(perm):
    return "[" + " ".join(str(perm[i]) for i in range(DIM)) + "]"


def write_full_table(out_dir, rows):
    """Write the raw full sweep table (PR artifact, NOT committed to the tree)."""
    os.makedirs(out_dir, exist_ok=True)
    fields = list(rows[0].keys())
    csv_path = os.path.join(out_dir, "realizable_image_sweep.csv")
    with open(csv_path, "w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)
    md_path = os.path.join(out_dir, "realizable_image_sweep.md")
    with open(md_path, "w") as handle:
        handle.write("# Realizable-image operation sweep (raw full table)\n\n")
        handle.write(f"- Operations swept: **{len(rows)}**\n")
        handle.write("- `gap_to_S3` = min over the 6 S_3 DW maps of ||U - g||; "
                     "`realizable := gap_to_S3 < 1e-7`.\n")
        handle.write("- `gap_to_I4` = ||U - I_4|| (the old single-point metric).\n\n")
        handle.write("| " + " | ".join(fields) + " |\n")
        handle.write("|" + "|".join(["---"] * len(fields)) + "|\n")
        for row in rows:
            handle.write("| " + " | ".join(_fmt(row[f]) for f in fields) + " |\n")
    return csv_path, md_path


# --------------------------------------------------------------------------- #
# Self-check: the verdicts the report rests on.
# --------------------------------------------------------------------------- #
def verify(image, sweep):
    rows_by_label = {r["label"]: r for r in sweep.rows}
    # The six DW maps close to S_3 (asserted inside certify()).
    assert len(image.maps) == 6
    # Of the 24 permutations exactly the 6 holonomy ones are realizable.
    verdict = sweep.permutation_verdict()
    assert verdict["total"] == 24 and verdict["realizable"] == 6, verdict
    # I_4 realizable (read both as the S_3 identity and the perm identity); a
    # Haar / Hadamard sample is not.
    assert rows_by_label["s3_0123"]["realizable"] == 1
    assert rows_by_label["perm_0123"]["realizable"] == 1
    assert rows_by_label["haar_0"]["realizable"] == 0
    assert rows_by_label["hadamard4"]["realizable"] == 0
    # The separator is clean: is_holonomy_perm has zero false +/-.
    separator = sweep.separator_table()
    key = "is_holonomy_perm (fixes [0] & permutes {1,2,3})"
    assert separator[key]["separates"], separator[key]


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--out", default=OUT_DIR,
                        help="dir for the raw full table (default /tmp/cobordism; "
                             "NOT committed).")
    parser.add_argument("--no-write", action="store_true",
                        help="skip writing the raw full table.")
    args = parser.parse_args()

    image = RealizableImage()
    perms = image.certify()
    machinery = BridgeMachinery()
    sweep = OperationSweep(image, machinery)
    sweep.run()
    verify(image, sweep)

    print_report(image, sweep, perms)
    if not args.no_write:
        csv_path, md_path = write_full_table(args.out, sweep.rows)
        print(f"{len(sweep.rows)} operations swept.")
        print(f"  raw CSV (PR artifact, not committed): {csv_path}")
        print(f"  raw MD  (PR artifact, not committed): {md_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
