# Copyright (c) 2026 Twin Vector Labs LLC.
# All rights reserved.

"""Non-invertible DW maps from non-cylinder cobordisms — beyond S₃ (#196).

The realizable Dijkgraaf–Witten ``T²→T²`` map image had been the invertible group
``S₃``: every buildable cobordism was a *mapping cylinder* (``twistedCylinder``,
#193), and a cylinder's DW map is always an invertible holonomy permutation.

``Cobordism.disjointUnion`` breaks out of that sector. The **disconnected
cap-and-create** cobordism

    W = ST ⊔ ST,   ST = S¹ × D²  (a solid torus, ∂ST = T²)

has ``∂W = T² ⊔ T²`` but a *disconnected* bulk (``b₀(W) = 2``), so it is not a
cylinder. Its DW state sum factorizes over the two components: each solid torus
contributes its boundary state ``|st⟩ ∈ Z(T²) = ℂ⁴`` (the longitude survives the
``H¹(ST)→H¹(∂ST)`` restriction, the meridian dies), and the two-component map is
the rank-1 outer product

    Z(W) = |st⟩⟨st|   (rank 1, det 0 — NON-invertible).

Here ``|st⟩ = [1, 1, 0, 0]`` in the ``map()`` flat-connection-class order (the
trivial class and the longitude class carry amplitude 1). This is asserted
against an independent numpy oracle that rebuilds ``|st⟩`` from the solid torus
through a separate GF(2)-cohomology code path and forms the outer product.

Enlarged image: the matrix algebra generated by the six ``S₃`` maps (the swap on
the 9-vertex product torus, the order-3 rotation on the 7-vertex Möbius torus,
#193/#194) **together with** ``Z(W)`` is a 10-dimensional subalgebra of the
16-dim ``End(ℂ⁴)`` — versus the 5-dimensional algebra the group ``S₃`` spans on
its own. The non-invertible sector doubles the realizable algebra.
"""

import unittest

import numpy as np

import tessera

cobordism = tessera.cobordism
DijkgraafWitten = cobordism.DijkgraafWitten
Cocycle = cobordism.Cocycle
Cobordism = cobordism.Cobordism


# --------------------------------------------------------------------------- #
# Fixtures (the established cobordism-test constructions).
# --------------------------------------------------------------------------- #
def _build(topology):
    signature = tessera.Signature(topology.dimension(), tessera.Lorentzian)
    metric = tessera.Metric(True, signature)
    spacetime = tessera.Spacetime(metric, tessera.CDT, 1.0, 1.0,
                                  tessera.PREFERRED, topology)
    spacetime.build()
    return spacetime


def _circle():
    # S¹ = ∂Δ², the minimal triangle-boundary circle (3 vertices).
    return tessera.SimplexBoundarySphere(1)


def _solid_torus():
    # ST = S¹ × D² (solid torus); ∂ST = S¹ × S¹ = T² (one boundary component).
    return _build(tessera.SimplicialProduct(_circle(), tessera.SolidSimplex(2)))


def _cap_and_create():
    # W = ST ⊔ ST: the disconnected cap-and-create cobordism T² → T².
    return Cobordism.disjointUnion(_solid_torus(), _solid_torus())


def _torus9_topology():
    # T² = S¹ × S¹, the 9-vertex symmetric product torus.
    return tessera.SimplicialProduct(_circle(), _circle())


def _torus9():
    return _build(_torus9_topology())


# φ(u, v) = (v, u) on the 3×3 product torus (productId = 3u+v): the order-2 swap.
_SWAP = [v * 3 + u for u in range(3) for v in range(3)]

# The minimal 7-vertex (Möbius) torus and its order-3 multiplier i ↦ 2i (mod 7).
_SEVEN_VERTEX_TRIANGLES = sorted({
    tuple(sorted(((i) % 7, (i + step) % 7, (i + 3) % 7)))
    for i in range(7) for step in (1, 2)})


def _seven_vertex_torus():
    signature = tessera.Signature(2, tessera.Lorentzian)
    metric = tessera.Metric(True, signature)
    spacetime = tessera.Spacetime(metric, tessera.CDT, 1.0, 1.0,
                                  tessera.PREFERRED, None)
    vertices = [spacetime.createVertex(i) for i in range(7)]
    for triangle in _SEVEN_VERTEX_TRIANGLES:
        spacetime.createSimplex([vertices[i] for i in triangle])
    return spacetime


def _multiplier(m, n):
    return [(m * i) % n for i in range(n)]


# --------------------------------------------------------------------------- #
# Independent numpy GF(2) cohomology oracle.
#
# Faithfully reimplements DijkgraafWitten::computeBoundary in pure numpy — the
# bulk H¹(W;ℤ₂) enumeration, the per-component H¹(Σ_i) class indexing
# (gf2Span(reps) residue order), the holonomy binning, and the ω product — so the
# *exact* amplitude vector / map matrix can be asserted through a separate code
# path. The C++ ChainComplex / boundaryFaces are used only for the raw
# combinatorial inputs (boundary maps + simplex tuples); all of the linear
# algebra and indexing is recomputed here.
# --------------------------------------------------------------------------- #
def _gf2_nullspace(matrix, cols):
    if matrix.size == 0:
        return [np.eye(cols, dtype=np.int64)[i] for i in range(cols)]
    a = (np.asarray(matrix, dtype=np.int64) & 1).copy()
    rows, _ = a.shape
    pivots, r = [], 0
    for col in range(cols):
        if r >= rows:
            break
        piv = next((i for i in range(r, rows) if a[i, col] & 1), None)
        if piv is None:
            continue
        a[[r, piv]] = a[[piv, r]]
        for i in range(rows):
            if i != r and (a[i, col] & 1):
                a[i] ^= a[r]
        pivots.append(col)
        r += 1
    is_pivot = [c in pivots for c in range(cols)]
    basis = []
    for free in range(cols):
        if is_pivot[free]:
            continue
        x = np.zeros(cols, dtype=np.int64)
        x[free] = 1
        for t, pc in enumerate(pivots):
            x[pc] = a[t, free] & 1
        basis.append(x)
    return basis


def _gf2_span(basis, cols):
    out = []
    for mask in range(1 << len(basis)):
        x = np.zeros(cols, dtype=np.int64)
        for b in range(len(basis)):
            if (mask >> b) & 1:
                x ^= basis[b]
        out.append(x)
    return out


def _gf2_residue(vector, span_rows):
    v = (np.asarray(vector, dtype=np.int64) & 1).copy()
    for row in span_rows:
        piv = int(np.argmax(row)) if row.any() else -1
        if piv >= 0 and (v[piv] & 1):
            v ^= row
    return v & 1


def _gf2_echelon(generators, cols):
    rows = []
    for gen in generators:
        v = _gf2_residue(gen, rows)
        if v.any():
            rows.append(v)
            rows.sort(key=lambda row: int(np.argmax(row)))
    return rows


def _cohomology_reps(cocycles, coboundaries, cols):
    span_rows = _gf2_echelon(coboundaries, cols)
    reps = []
    for z in cocycles:
        if _gf2_residue(z, span_rows).any():
            reps.append(np.asarray(z, dtype=np.int64) & 1)
            span_rows = _gf2_echelon(
                list(span_rows) + [np.asarray(z, dtype=np.int64) & 1], cols)
    return reps


def _omega(kind, a, b, c):
    if kind == "trivial":
        return 1.0
    if kind == "sign":
        return -1.0 if (a & b & c) else 1.0
    raise ValueError(kind)


def _dw_amplitudes(spacetime, kind="trivial"):
    """(dims, amplitudes) of Z(∂W) — a faithful numpy port of computeBoundary."""
    chain = cobordism.ChainComplex.fromSpacetime(spacetime)
    num_edges = chain.numSimplices(1)
    num_triangles = chain.numSimplices(2)

    boundary2 = (np.asarray(chain.boundaryMatrix(2), dtype=np.int64)
                 .reshape(num_edges, num_triangles)) & 1     # edges × triangles
    cocycle_basis = _gf2_nullspace(boundary2.T, num_edges)   # Z¹ = ker(∂₂ᵀ)

    edges = [tuple(e) for e in chain.kSimplexVertices(1)]
    edge_index = {e: i for i, e in enumerate(edges)}
    vertex_ids = [int(v[0]) for v in chain.kSimplexVertices(0)]
    coboundary_basis = [
        np.array([1 if vid in e else 0 for e in edges], dtype=np.int64)
        for vid in vertex_ids]
    bulk_reps = _cohomology_reps(cocycle_basis, coboundary_basis, num_edges)
    bulk_classes = _gf2_span(bulk_reps, num_edges)

    btris = [tuple(t) for t in Cobordism.boundaryFaces(spacetime)]
    raw = Cobordism.connectedComponents([list(t) for t in btris])
    components = sorted(sorted(tuple(t) for t in comp) for comp in raw)

    indexers = []
    for comp in components:
        comp_edges = sorted({pair for tri in comp
                             for pair in ((tri[0], tri[1]), (tri[0], tri[2]),
                                          (tri[1], tri[2]))})
        local_index = {e: i for i, e in enumerate(comp_edges)}
        n_local = len(comp_edges)
        local_cob = np.zeros((len(comp), n_local), dtype=np.int64)
        for t, tri in enumerate(comp):
            for pair in ((tri[0], tri[1]), (tri[0], tri[2]), (tri[1], tri[2])):
                local_cob[t, local_index[pair]] = 1
        local_cocycles = _gf2_nullspace(local_cob, n_local)
        comp_verts = sorted({v for tri in comp for v in tri})
        local_cob_basis = [
            np.array([1 if v in e else 0 for e in comp_edges], dtype=np.int64)
            for v in comp_verts]
        local_reps = _cohomology_reps(local_cocycles, local_cob_basis, n_local)
        local_classes = _gf2_span(local_reps, n_local)
        cob_rows = _gf2_echelon(local_cob_basis, n_local)
        class_of_residue = {tuple(_gf2_residue(c, cob_rows)): i
                            for i, c in enumerate(local_classes)}
        local_to_global = [edge_index[e] for e in comp_edges]
        indexers.append((local_to_global, cob_rows, class_of_residue,
                         len(local_classes)))

    dims = [idx[3] for idx in indexers]
    amplitudes = np.zeros(int(np.prod(dims)) if dims else 1, dtype=float)
    tets = [tuple(t) for t in chain.orientedTopSimplices()]
    for g in bulk_classes:
        joint = 0
        for local_to_global, cob_rows, class_of_residue, dim in indexers:
            local = np.array([g[i] for i in local_to_global], dtype=np.int64)
            joint = joint * dim + class_of_residue[
                tuple(_gf2_residue(local, cob_rows))]
        weight = 1.0
        for tet in tets:
            g01 = int(g[edge_index[(tet[0], tet[1])]])
            g12 = int(g[edge_index[(tet[1], tet[2])]])
            g23 = int(g[edge_index[(tet[2], tet[3])]])
            weight *= _omega(kind, g01, g12, g23)
        amplitudes[joint] += weight
    return dims, amplitudes


def _solid_torus_state_oracle(kind="trivial"):
    """|st⟩ ∈ Z(T²) — the solid torus boundary vector, built independently."""
    dims, amplitudes = _dw_amplitudes(_solid_torus(), kind)
    assert dims == [4], dims
    return amplitudes


def _dw_map(spacetime, cocycle=Cocycle.Trivial):
    return np.asarray(DijkgraafWitten(spacetime, cocycle).map())


# --------------------------------------------------------------------------- #
# Algebra-dimension helper (the realizable-image characterization).
# --------------------------------------------------------------------------- #
def _algebra_dimension(generators):
    """dim of the unital associative algebra ⟨generators⟩ ⊆ End(ℂ⁴)."""
    def flat(matrix):
        return np.asarray(matrix, dtype=complex).reshape(-1)

    basis = [flat(np.eye(4))]

    def independent(vector):
        stacked = np.array(basis + [vector])
        return np.linalg.matrix_rank(stacked, tol=1e-9) > len(basis)

    for generator in generators:
        v = flat(generator)
        if independent(v):
            basis.append(v)

    changed = True
    while changed:
        changed = False
        matrices = [b.reshape(4, 4) for b in basis]
        for a in matrices:
            for b in matrices:
                v = flat(a @ b)
                if independent(v):
                    basis.append(v)
                    changed = True
    return len(basis)


def _s3_group():
    """The six S₃ DW maps, rebuilt from twistedCylinder (#193/#194)."""
    swap = _dw_map(Cobordism.twistedCylinder(_torus9(), _SWAP)).real
    rotation = _dw_map(
        Cobordism.twistedCylinder(_seven_vertex_torus(),
                                  _multiplier(2, 7))).real
    identity = np.eye(4)
    group, frontier = [identity], [identity]

    def known(matrix):
        return any(np.allclose(matrix, seen, atol=1e-9) for seen in group)

    while frontier:
        element = frontier.pop()
        for generator in (swap, rotation):
            for product in (generator @ element, element @ generator):
                if not known(product):
                    group.append(product)
                    frontier.append(product)
    return group


# --------------------------------------------------------------------------- #
# The headline: a rank-1, non-invertible DW map.
# --------------------------------------------------------------------------- #
class TestCapAndCreateIsRankOne(unittest.TestCase):

    def test_map_is_four_by_four(self):
        self.assertEqual(_dw_map(_cap_and_create()).shape, (4, 4))

    def test_map_is_rank_one_and_non_invertible(self):
        Z = _dw_map(_cap_and_create()).real
        self.assertEqual(np.linalg.matrix_rank(Z, tol=1e-9), 1)
        self.assertAlmostEqual(float(np.linalg.det(Z)), 0.0, places=9)

    def test_map_is_not_the_identity_or_any_permutation(self):
        # The whole point of #196: a non-permutation, so outside S₃.
        Z = _dw_map(_cap_and_create()).real
        self.assertFalse(np.allclose(Z, np.eye(4)))
        column_sums = np.round(Z.sum(axis=0)).astype(int)
        self.assertFalse(np.array_equal(column_sums, np.ones(4, dtype=int)))

    def test_map_equals_solid_torus_outer_product(self):
        # Z(W) = |st⟩⟨st|, with |st⟩ rebuilt independently in numpy.
        st = _solid_torus_state_oracle()
        np.testing.assert_allclose(_dw_map(_cap_and_create()).real,
                                   np.outer(st, st), atol=1e-9)

    def test_map_matches_full_independent_oracle(self):
        # The whole two-component map, recomputed through the numpy port.
        dims, amplitudes = _dw_amplitudes(_cap_and_create())
        self.assertEqual(dims, [4, 4])
        np.testing.assert_allclose(_dw_map(_cap_and_create()).real,
                                   amplitudes.reshape(4, 4), atol=1e-9)

    def test_solid_torus_state_is_two_ones(self):
        # |st⟩ = [1,1,0,0]: trivial class + the surviving longitude class.
        st = _solid_torus_state_oracle()
        np.testing.assert_allclose(st, np.array([1.0, 1.0, 0.0, 0.0]),
                                   atol=1e-9)
        self.assertAlmostEqual(st[0], 1.0, places=9)  # trivial class survives
        self.assertEqual(int(np.count_nonzero(np.round(st, 6))), 2)

    def test_map_is_a_rank_one_outer_product_structurally(self):
        # P = |st⟩⟨st|: symmetric, PSD, trace = ‖st‖² = 2, P² = ‖st‖² P.
        Z = _dw_map(_cap_and_create()).real
        np.testing.assert_allclose(Z, Z.T, atol=1e-9)            # symmetric
        self.assertAlmostEqual(float(np.trace(Z)), 2.0, places=9)
        np.testing.assert_allclose(Z @ Z, 2.0 * Z, atol=1e-9)   # P² = ‖st‖² P
        eigvals = np.linalg.eigvalsh(Z)
        self.assertGreaterEqual(eigvals.min(), -1e-9)           # PSD

    def test_sign_cocycle_gives_the_same_map(self):
        # The mod-2 cup cube vanishes on the solid tori, so Sign agrees.
        st_sign = _solid_torus_state_oracle("sign")
        np.testing.assert_allclose(_dw_map(_cap_and_create(), Cocycle.Sign).real,
                                   np.outer(st_sign, st_sign), atol=1e-9)
        np.testing.assert_allclose(_dw_map(_cap_and_create(), Cocycle.Sign),
                                   _dw_map(_cap_and_create(), Cocycle.Trivial),
                                   atol=1e-9)


# --------------------------------------------------------------------------- #
# The bulk really is disconnected (so W is NOT a mapping cylinder).
# --------------------------------------------------------------------------- #
class TestBulkIsDisconnected(unittest.TestCase):

    def test_bulk_betti_zero_is_two_components(self):
        # b₀(W) = 2: two solid tori. A cylinder T²×I has b₀ = 1 — this is the
        # structural witness that W is not a mapping cylinder.
        betti = cobordism.ChainComplex.fromSpacetime(_cap_and_create()).bettiNumbers()
        self.assertEqual(betti[0], 2)
        self.assertEqual(betti[1], 2)  # H¹ = ℤ₂² (one longitude per solid torus)

    def test_boundary_dimensions_are_two_tori(self):
        dims = DijkgraafWitten(_cap_and_create(),
                               Cocycle.Trivial).boundaryDimensions()
        self.assertEqual(list(dims), [4, 4])  # Z(T²) ⊗ Z(T²)

    def test_boundary_has_two_torus_components(self):
        faces = Cobordism.boundaryFaces(_cap_and_create())
        components = Cobordism.connectedComponents([list(f) for f in faces])
        self.assertEqual(len(components), 2)
        for component in components:  # each a closed T² (χ = 0)
            verts = {v for tri in component for v in tri}
            edges = {tuple(sorted(pair)) for tri in component
                     for pair in ((tri[0], tri[1]), (tri[0], tri[2]),
                                  (tri[1], tri[2]))}
            self.assertEqual(len(verts) - len(edges) + len(component), 0)

    def test_disjoint_union_does_not_collide_vertices(self):
        # |V(ST ⊔ ST)| = 2·|V(ST)|: the two copies share no vertex id.
        solid = _solid_torus()
        n_one = cobordism.ChainComplex.fromSpacetime(solid).numSimplices(0)
        n_union = cobordism.ChainComplex.fromSpacetime(
            Cobordism.disjointUnion(solid, solid)).numSimplices(0)
        self.assertEqual(n_union, 2 * n_one)


# --------------------------------------------------------------------------- #
# The enlarged realizable image: ⟨S₃, |st⟩⟨st|⟩ ⊆ End(ℂ⁴).
# --------------------------------------------------------------------------- #
class TestEnlargedImage(unittest.TestCase):

    def test_s3_alone_spans_a_five_dimensional_algebra(self):
        # The six permutation maps (fix [0], permute the 3 nontrivial classes)
        # span a 5-dim subalgebra of End(ℂ⁴): ℂ ⊕ M₂(ℂ) under ℂ⁴ = 2·triv ⊕ std.
        group = _s3_group()
        self.assertEqual(len(group), 6)
        self.assertEqual(_algebra_dimension(group), 5)

    def test_new_map_enlarges_the_algebra_to_ten_dimensions(self):
        # ⟨S₃, |st⟩⟨st|⟩ is 10-dimensional — the non-invertible map doubles the
        # realizable algebra (5 → 10), strictly inside the 16-dim End(ℂ⁴).
        group = _s3_group()
        projector = _dw_map(_cap_and_create()).real
        enlarged = _algebra_dimension(group + [projector])
        self.assertEqual(enlarged, 10)
        self.assertGreater(enlarged, 6)   # strictly beyond the 6-element group
        self.assertGreater(enlarged, 5)   # strictly beyond ⟨S₃⟩
        self.assertLess(enlarged, 16)     # a proper subalgebra of End(ℂ⁴)

    def test_new_map_is_outside_s3(self):
        # |st⟩⟨st| is not one of the six (invertible) S₃ maps.
        projector = _dw_map(_cap_and_create()).real
        self.assertFalse(any(np.allclose(projector, g, atol=1e-9)
                             for g in _s3_group()))


# --------------------------------------------------------------------------- #
# disjointUnion guards.
# --------------------------------------------------------------------------- #
class TestDisjointUnionGuards(unittest.TestCase):

    def test_rejects_empty_input(self):
        empty = tessera.Spacetime()
        with self.assertRaises((ValueError, RuntimeError)):
            Cobordism.disjointUnion(empty, _solid_torus())

    def test_rejects_mismatched_top_dimension(self):
        # A solid torus (3-manifold) and a bare surface (2-manifold) differ in
        # top dimension and cannot be disjoint-unioned as same-dim complexes.
        with self.assertRaises((ValueError, RuntimeError)):
            Cobordism.disjointUnion(_solid_torus(), _torus9())


if __name__ == "__main__":
    unittest.main()
