# MIT License
# Copyright (c) 2025 Andrew Kelleher
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""The enriched realizable DW image is exactly S_3 = GL(2,Z_2) (#194).

With the twisted-cylinder builder (#193) the realizable Dijkgraaf-Witten
2-boundary map image grew from the single point {I_4} to the 6-element S_3 of
holonomy-class permutations. This pins the re-run sweep's claims:

  * the swap (order 2) and the 3-cycle (order 3) DW maps generate, by matrix
    multiplication, a group of exactly 6 elements -- the full S_3 on the three
    non-trivial classes, fixing the trivial one;
  * of the 24 of S_4's 4x4 permutation matrices, exactly the 6 that fix index 0
    are realizable (gap_to_S3 -> 0); the other 18 are not;
  * I_4 is realizable; a Haar / Hadamard sample is not;
  * the separator is realizable(U) <=> U is a 0/1 permutation fixing the trivial
    class -- equivalently a GL(2,Z_2)-linear automorphism of H^1(T^2;Z_2).

The DW maps are built through the genuine ``Cobordism.twistedCylinder`` +
``DijkgraafWitten.map`` machinery (the #193 fixtures, reused so the two
generators share the holonomy-class indexing) and the operation reading goes
through ``ChoiJamiolkowski.transitionAmplitude`` -- a separate code path from the
committed example, which is additionally loaded and asked to self-verify.
"""

import importlib.util
import itertools
import os
import unittest

import numpy as np

import tessera

cobordism = tessera.cobordism
DijkgraafWitten = cobordism.DijkgraafWitten
Cocycle = cobordism.Cocycle
Cobordism = cobordism.Cobordism
ChoiJamiolkowski = tessera.quantum.ChoiJamiolkowski

DIM = 4
TOL = 1e-7


# --------------------------------------------------------------------------- #
# Fixtures -- the #193 idiom (the two generator surfaces).
# --------------------------------------------------------------------------- #
def _build(topology):
    signature = tessera.Signature(topology.dimension(), tessera.Lorentzian)
    metric = tessera.Metric(True, signature)
    spacetime = tessera.Spacetime(metric, tessera.CDT, 1.0, 1.0,
                                  tessera.PREFERRED, topology)
    spacetime.build()
    return spacetime


def _circle():
    return tessera.SimplexBoundarySphere(1)


def _torus_topology():
    return tessera.SimplicialProduct(_circle(), _circle())


def _product_torus():
    return _build(_torus_topology())


_SWAP = [v * 3 + u for u in range(3) for v in range(3)]

_SEVEN_VERTEX_TRIANGLES = sorted({
    tuple(sorted(((i) % 7, (i + step) % 7, (i + 3) % 7)))
    for i in range(7) for step in (1, 2)})


def _seven_vertex_torus():
    signature = tessera.Signature(2, tessera.Lorentzian)
    metric = tessera.Metric(True, signature)
    spacetime = tessera.Spacetime(metric, tessera.CDT, 1.0, 1.0,
                                  tessera.PREFERRED, None)
    vertices = [spacetime.createVertex(i) for i in range(7)]
    for triangle in _SEVEN_VERTEX_TRIANGLES:
        spacetime.createSimplex([vertices[i] for i in triangle])
    return spacetime


def _multiplier(m, n):
    return [(m * i) % n for i in range(n)]


def _twisted_map(surface, phi, cocycle=Cocycle.Trivial):
    twisted = Cobordism.twistedCylinder(surface, phi)
    return np.asarray(DijkgraafWitten(twisted, cocycle).map()).real


def _permutation_matrix(perm):
    matrix = np.zeros((DIM, DIM))
    for row, col in enumerate(perm):
        matrix[row, col] = 1.0
    return matrix


def _close_group(generators):
    """The matrix group generated by `generators` (breadth-first closure)."""
    def key(matrix):
        return tuple(np.round(matrix).astype(int).reshape(-1))
    identity = np.eye(DIM)
    group = {key(identity): identity}
    frontier = [identity]
    while frontier:
        element = frontier.pop()
        for generator in generators:
            product = np.round(generator @ element)
            if key(product) not in group:
                group[key(product)] = product
                frontier.append(product)
    return list(group.values())


def _realizable_maps():
    """The realizable image: <DW(swap), DW(3-cycle)> as a list of 4x4 matrices."""
    swap = _twisted_map(_product_torus(), _SWAP)
    three_cycle = _twisted_map(_seven_vertex_torus(), _multiplier(2, 7))
    return swap, three_cycle, _close_group([swap, three_cycle])


def _gap_to_s3(U, image):
    return float(min(np.linalg.norm(np.asarray(U) - g) for g in image))


def _haar(seed):
    rng = np.random.default_rng(seed)
    z = (rng.standard_normal((DIM, DIM))
         + 1j * rng.standard_normal((DIM, DIM))) / np.sqrt(2)
    q, r = np.linalg.qr(z)
    return q @ np.diag(np.diag(r) / np.abs(np.diag(r)))


def _hadamard4():
    h2 = np.array([[1, 1], [1, -1]], dtype=complex) / np.sqrt(2)
    return np.kron(h2, h2)


# --------------------------------------------------------------------------- #
# The six DW maps close to S_3.
# --------------------------------------------------------------------------- #
class TestRealizableImageClosesToS3(unittest.TestCase):

    def setUp(self):
        self.swap, self.three_cycle, self.image = _realizable_maps()

    def test_generators_are_the_expected_transposition_and_three_cycle(self):
        # swap: fixes [0],[a+b], transposes [a]<->[b]  (the modular S).
        np.testing.assert_allclose(self.swap, _permutation_matrix((0, 2, 1, 3)),
                                   atol=1e-9)
        # 3-cycle: fixes [0], cycles [a]->[b]->[a+b].
        np.testing.assert_allclose(self.three_cycle,
                                   _permutation_matrix((0, 2, 3, 1)), atol=1e-9)

    def test_group_closes_to_six_elements(self):
        # <swap, 3-cycle> is S_3 -- order 6, strictly larger than the old {I_4}.
        self.assertEqual(len(self.image), 6)

    def test_every_realizable_map_is_a_permutation_fixing_the_trivial_class(self):
        for g in self.image:
            self.assertTrue(np.all(np.isclose(g, 0) | np.isclose(g, 1)))
            np.testing.assert_array_equal(np.round(g.sum(axis=0)).astype(int),
                                          np.ones(DIM, dtype=int))
            np.testing.assert_array_equal(np.round(g.sum(axis=1)).astype(int),
                                          np.ones(DIM, dtype=int))
            self.assertAlmostEqual(g[0, 0], 1.0, places=9)  # fixes class [0]

    def test_realizable_set_equals_the_index0_fixing_permutations(self):
        # The realizable image is exactly the 6 of S_4's permutation matrices
        # that fix index 0 (and so permute {1,2,3}) -- the GL(2,Z_2) rep.
        fixers = [_permutation_matrix(p)
                  for p in itertools.permutations(range(DIM)) if p[0] == 0]
        self.assertEqual(len(fixers), 6)
        for fixer in fixers:
            self.assertTrue(any(np.allclose(fixer, g) for g in self.image))

    def test_group_is_closed_under_product_and_inverse(self):
        def key(matrix):
            return tuple(np.round(matrix).astype(int).reshape(-1))
        keys = {key(g) for g in self.image}
        for a in self.image:
            self.assertIn(key(a.T), keys)                 # inverse = transpose
            for b in self.image:
                self.assertIn(key(np.round(a @ b)), keys)  # closed under product

    def test_image_is_isomorphic_to_s3_not_abelian(self):
        # S_3 is non-abelian: swap and 3-cycle do not commute.
        self.assertFalse(np.allclose(self.swap @ self.three_cycle,
                                     self.three_cycle @ self.swap))


# --------------------------------------------------------------------------- #
# Exactly 6 of the 24 permutations are realizable; the clean separation.
# --------------------------------------------------------------------------- #
class TestPermutationSeparation(unittest.TestCase):

    def setUp(self):
        _, _, self.image = _realizable_maps()

    def test_exactly_six_of_twentyfour_permutations_are_realizable(self):
        realizable = []
        for perm in itertools.permutations(range(DIM)):
            P = _permutation_matrix(perm)
            if _gap_to_s3(P, self.image) < TOL:
                realizable.append(perm)
        self.assertEqual(len(realizable), 6)
        # ... and they are precisely the ones that fix index 0.
        self.assertTrue(all(perm[0] == 0 for perm in realizable))
        self.assertEqual({perm[0] for perm in itertools.permutations(range(DIM))
                          if _gap_to_s3(_permutation_matrix(perm), self.image)
                          >= TOL},
                         {1, 2, 3})  # every non-realizable permutation moves [0]

    def test_identity_is_realizable(self):
        self.assertLess(_gap_to_s3(np.eye(DIM), self.image), TOL)

    def test_haar_and_hadamard_are_not_realizable(self):
        for seed in range(6):
            self.assertGreater(_gap_to_s3(_haar(1000 + seed), self.image), 1e-2)
        self.assertGreater(_gap_to_s3(_hadamard4(), self.image), 1e-2)

    def test_some_two_qubit_gates_are_realizable_holonomy_permutations(self):
        # SWAP == the swap (12); CNOT == the transposition (23): both fix [0].
        swap_gate = _permutation_matrix((0, 2, 1, 3))
        cnot = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]],
                        dtype=float)
        self.assertLess(_gap_to_s3(swap_gate, self.image), TOL)
        self.assertLess(_gap_to_s3(cnot, self.image), TOL)
        # CZ (a sign, not a permutation) is not realizable.
        cz = np.diag([1.0, 1.0, 1.0, -1.0])
        self.assertGreater(_gap_to_s3(cz, self.image), 1e-2)

    def test_gap_to_s3_is_at_most_gap_to_i4(self):
        # I_4 is one of the six realizable maps, so distance-to-S_3 never exceeds
        # distance-to-I_4 -- the metric the gap is now governed by.
        for seed in range(8):
            U = _haar(2000 + seed)
            gap_s3 = _gap_to_s3(U, self.image)
            gap_i4 = float(np.linalg.norm(U - np.eye(DIM)))
            self.assertLessEqual(gap_s3, gap_i4 + 1e-12)


# --------------------------------------------------------------------------- #
# The gap is read through the genuine ChoiJamiolkowski machinery.
# --------------------------------------------------------------------------- #
class TestGenuineMachineryReading(unittest.TestCase):

    def setUp(self):
        _, _, self.image = _realizable_maps()
        self.space = cobordism.BoundaryStateSpace(_product_torus())
        self.assertEqual(self.space.boundaryDimension(), DIM)
        self.basis = [np.eye(DIM, dtype=complex)[i] for i in range(DIM)]

    def _amplitude_matrix(self, U):
        Uflat = [complex(z) for z in np.asarray(U, dtype=complex).reshape(-1)]
        amplitudes = np.empty((DIM, DIM), dtype=complex)
        for i in range(DIM):
            ei = [complex(z) for z in self.basis[i]]
            for j in range(DIM):
                ej = [complex(z) for z in self.basis[j]]
                amplitudes[i, j] = complex(
                    ChoiJamiolkowski.transitionAmplitude(ei, Uflat, ej, DIM, DIM))
        return amplitudes

    def test_cylinder_state_sum_reads_as_identity(self):
        # Z_DW of the product cylinder, read via DijkgraafWitten.amplitude over
        # the holonomy basis (BoundaryStateSpace.state), is I_4 -- the realizable
        # identity, anchoring the gap metrics in the machinery.
        cylinder = _build(tessera.SimplicialProduct(_torus_topology(),
                                                    tessera.SolidSimplex(1)))
        dw = DijkgraafWitten(cylinder, Cocycle.Trivial)
        z_dw = np.array(
            [[complex(dw.amplitude(self.space.state(self.basis[i]),
                                   self.space.state(self.basis[j])))
              for j in range(DIM)] for i in range(DIM)])
        np.testing.assert_allclose(z_dw, np.eye(DIM), atol=1e-9)

    def test_choi_reading_reproduces_the_operation_and_its_gap(self):
        # The transition-amplitude reading reconstructs U over the basis, so the
        # gap computed through the machinery equals the direct matrix gap.
        for seed in range(4):
            U = _haar(3000 + seed)
            amplitudes = self._amplitude_matrix(U)
            np.testing.assert_allclose(amplitudes, U, atol=1e-9)
            self.assertAlmostEqual(_gap_to_s3(amplitudes, self.image),
                                   _gap_to_s3(U, self.image), places=9)


# --------------------------------------------------------------------------- #
# The committed example self-verifies.
# --------------------------------------------------------------------------- #
_HERE = os.path.dirname(os.path.abspath(__file__))
_SCRIPT = os.path.normpath(os.path.join(
    _HERE, "..", "..", "examples", "cobordism", "realizable_image_sweep.py"))


def _load_example():
    spec = importlib.util.spec_from_file_location("realizable_image_sweep",
                                                  _SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class TestCommittedExampleSelfVerifies(unittest.TestCase):

    def test_script_exists(self):
        self.assertTrue(os.path.isfile(_SCRIPT), _SCRIPT)

    def test_example_runs_and_verifies(self):
        module = _load_example()
        image = module.RealizableImage()
        perms = image.certify()                       # asserts S_3 closure
        self.assertEqual(len(perms), 6)
        machinery = module.BridgeMachinery()
        sweep = module.OperationSweep(image, machinery)
        sweep.run()
        module.verify(image, sweep)                   # the report's verdicts

        verdict = sweep.permutation_verdict()
        self.assertEqual((verdict["total"], verdict["realizable"]), (24, 6))
        self.assertTrue(module.is_holonomy_permutation(np.eye(DIM)))
        self.assertFalse(module.is_holonomy_permutation(_hadamard4()))

    def test_example_separator_is_clean(self):
        module = _load_example()
        image = module.RealizableImage()
        image.certify()
        sweep = module.OperationSweep(image, module.BridgeMachinery())
        sweep.run()
        key = "is_holonomy_perm (fixes [0] & permutes {1,2,3})"
        cell = sweep.separator_table()[key]
        # No false positives, no false negatives: the separator is exact.
        self.assertEqual(cell["pred_notwork"], 0)
        self.assertEqual(cell["notpred_work"], 0)
        self.assertTrue(cell["separates"])


if __name__ == "__main__":
    unittest.main()
